# Generated by Django 5.0.4 on 2024-05-05 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionTree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField()),
                ('url', models.CharField()),
                ('data', models.TextField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
