# Generated by Django 5.0.4 on 2024-05-05 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionTree', '0003_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionqueue',
            name='question_id',
            field=models.IntegerField(null=True),
        ),
    ]
