# Generated by Django 5.0.4 on 2024-05-05 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionTree', '0004_questionqueue_question_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionqueue',
            name='question_name',
            field=models.CharField(null=True),
        ),
    ]
