# Generated by Django 5.0.4 on 2024-05-08 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionTree', '0006_question_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionqueue',
            name='username',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
    ]
