# Generated by Django 5.0.4 on 2024-05-15 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionTree', '0007_questionqueue_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Start',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activate', models.BooleanField(default=False)),
            ],
        ),
    ]
